### ISSUE TITLE
Compile Scittle plugins in :advanced mode

### ISSUE THREAD

**Issue by kloimhardt** [kloimhardt/lisp-webscript-examples#1]
in Sablono, namespace `sablono.interpreter`, line 22

cljs original: `(.setState component next-state)`
js result with :simple optimization: `a.setState(f)`
js :advanced optim.: `a.Ci(f)`

where this Ci throws a `not defined` error. Apparently `setState()` gets eliminated by google-closure advanced compilation.

**Comment by bendlas** [comment]
Yes, `.setState` needs to go to externs in this case.

Before `:infer-externs`, you'd put something like

```js
var Component = {};
Component.setState = function () {};
```

into the externs file. Nowaday's, with shadow, you'd put `:infer-externs :auto` and add `^js` metadata to your forms:

```cljs
(.setState ^js component next-state)
```

see https://code.thheller.com/blog/shadow-cljs/2017/11/06/improved-externs-inference.html

**Comment by kloimhardt** [comment]
:advanced compile works splendid now
