### ISSUE TITLE
Use testing functions from phel

### ISSUE THREAD

**Issue by Chemaclass** [kloimhardt/lisp-webscript-examples#2]
I saw that you have your own defined "tests" function in your phel scripts (for example https://github.com/kloimhardt/lisp-webscript-examples/blob/main/phel/little-clojure/core.phel), but you know that phel has its own library for tests, right?

Check this out: https://phel-lang.org/documentation/testing/#defining-tests

**Comment by kloimhardt** [comment]
Tests will be implemented the proper way.

Thank you for the code review. I'd love to get as much feedback as possible. I knew in the back of my head that the test library exists, but was down the rabbit hole at the time of writing and then forgot.

**Comment by kloimhardt** [comment]
tests properly implemented
