### ISSUE TITLE
Can not resolve alias 'qlkit' in keyword: ::qlkit/env

### ISSUE THREAD

**Issue by Chemaclass** [kloimhardt/lisp-webscript-examples#6]
## Context
I did `composer update` to ensure I have the latest `main` and all dependencies updated.

## Problem
When I run `./vendor/bin/phel test`, I get `Can not resolve alias 'qlkit' in keyword: ::qlkit/env`
<img width="1056" alt="Screenshot 2021-12-24 at 10 58 59" src="https://user-images.githubusercontent.com/5256287/147342727-a0445b53-7523-4116-a46a-bdd46d851491.png">

Do you have the same issue in your local?

**Comment by kloimhardt** [comment]
Yes, I could reproduce the failed test. It is fixed in commit 21414ce.
